### ISSUE TITLE
Camera calibration dataset / pinhole camera model

### ISSUE THREAD

**Issue by JonasBchrt** [HKUST-Aerial-Robotics/GVINS-Dataset#7]
@shaozu thank you for making these datasets available to the public.
We would like to run code on your dataset that supports only the pinhole camera model, not the Mei model. Do you think you could provide a calibration dataset such that we can run kalibr and use the model that we support? Or maybe you have calibrated a pinhole camera model yourself already or it would be very easy for you to do?

**Comment by shaozu** [comment]
@JonasBchrt below please find the parameters for the pinhole model.

### left 
```
%YAML:1.0

#left camera calibration 
model_type: PINHOLE
camera_name: cam1
image_width: 752
image_height: 480
distortion_parameters:
   k1: -0.295269
   k2: 0.085067
   p1: 0.000352
   p2: -0.000219
projection_parameters:
   fx: 468.157508
   fy: 467.978898
   cx: 382.180503
   cy: 214.028724
```

### right
```
%YAML:1.0

#right camera calibration 
model_type: PINHOLE
camera_name: cam0
image_width: 752
image_height: 480
distortion_parameters:
   k1: -0.2997493046323177
   k2: 0.09538277522623304
   p1: -3.949561182735437e-05
   p2: -0.0003873561868834772
projection_parameters:
   fx: 470.5799808597001
   fy: 470.8173735966212
   cx: 359.6496137621658
   cy: 250.2687221608846
```
